### ISSUE TITLE
Adding Layout

### ISSUE THREAD

**Issue by ak3264114** [BhattAnsh/Quiz-Quest#1]
hi @BhattAnsh ,
i can add layout in your fronted which include navbar and footer

please assign this to me under GSSOC Extended 2024 :)

![image](https://github.com/user-attachments/assets/32aed1e0-a1b0-4dba-8a08-99a809eef1f2)

**Comment by BhattAnsh** [comment]
I have a design ready for the project you have to work accordingly for that 
![Screenshot 2024-07-10 155923](https://github.com/user-attachments/assets/1f8b601e-4a60-47b5-83fa-d02510cd9dd5)
![Screenshot 2024-07-10 160007](https://github.com/user-attachments/assets/814271df-01c7-42ec-99e2-8554d1602e5a)
![Screenshot 2024-07-10 160037](https://github.com/user-attachments/assets/17207bfe-3473-4fd6-ad60-8e4705bb4055)
![Screenshot 2024-07-10 160101](https://github.com/user-attachments/assets/d1602487-d0e9-40f6-a702-313ebe160574)

**Comment by Harshitraaaj** [comment]
you have every images that you shown here ?
