### ISSUE TITLE
Design Home page

### ISSUE THREAD

**Issue by BaraniVA** [BhattAnsh/Quiz-Quest#10]
I would like to build the front end for the home page of the QuizQuest application. This will include designing and implementing the user interface to ensure a seamless and interactive user experience.

Tasks
Design the layout and structure of the home page.
Implement the UI components using HTML, CSS, and JavaScript.
Ensure the home page is responsive and accessible.
Integrate any necessary functionalities to enhance user interaction.
Expected Outcome
A fully functional and visually appealing home page that aligns with the overall design and user experience of the QuizQuest application.

**Comment by BaraniVA** [comment]
Please assign this to me with the labels so i can start working on it.

**Comment by BhattAnsh** [comment]
@BaraniVA thanks for you suggestion join our discord take you role and we will discuss there you will get people working with you okay? https://discord.gg/XBBgKkBT

**Comment by geetanjalidubey9** [comment]
pls assign this task to me
