### ISSUE TITLE
BUG: Login btn in navbar not working

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#100]
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: When  we click on login btn in navbar it will not redirect to login form

**Description**:
- **Steps to Reproduce**:
  1. Edit the functionality of login form in navbar.

- **Expected Result**: When we click to login btn on navbar then it will redirect to login form of website.
- **Actual Result**: Now when we click on navbar then it will not work

- **Screenshots**: (if applicable)
  

https://github.com/user-attachments/assets/62e1f0be-40df-4da0-a31a-b368fb7a4e06

**Environment**:
- **Operating System**: (Windows)
- **Browser**: (Chrome)
- **Version**: (e.g., QuizQuest v1.0)

**Additional Information**: (any other relevant details)
Please assign this task to me:)

**Comment by BhattAnsh** [comment]
start working on this and link the login page
