### ISSUE TITLE
BUG: Footer alignment is bad

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#101]
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: Footer bad-design

**Description**:
- **Steps to Reproduce**:
1.. Edit the css of footer
- **Expected Result**: Now footer one component in extreme left and one component is extreme right and no equal spacing in between.
- **Actual Result**: Footer is not good aligned.
- 
- **Screenshots**: (if applicable)
  
![footer12](https://github.com/user-attachments/assets/0444a2dd-c48b-4b28-a7a0-e9d6a2ce8315)

**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this task to me:)

**Comment by BhattAnsh** [comment]
yep start working on this
