### ISSUE TITLE
About page...

### ISSUE THREAD

**Issue by Hemraj-7** [BhattAnsh/Quiz-Quest#104]
Quiz-Quest platform doesn't have about page. it is looking bad.

![Screenshot 2024-10-22 131951](https://github.com/user-attachments/assets/b4f73ca7-5be0-495d-bc48-a523a6a9b511)

I want to add about page and add information about the Quiz-Quest Platform.

Assign me the task with appropriate labels
Thank you

**Comment by Wahid7852** [comment]
@Hemraj-7 gonna work on this still? And what are you going to do for this?

**Comment by Hemraj-7** [comment]
> @Hemraj-7 gonna work on this still? And what are you going to do for this?

If you assign me I'll add the website information in the  about page.

**Comment by techy4shri** [comment]
@BhattAnsh check this please.

**Comment by BhattAnsh** [comment]
@Hemraj-7 can you tell us the design you have in your mind for the About page because I have one more person wants to work on the same issue.....

**Comment by Hemraj-7** [comment]
> @Hemraj-7 can you tell us the design you have in your mind for the About page because I have one more person wants to work on the same issue.....

I will update this content and add to the about page.
![Screenshot 2024-11-02 235254](https://github.com/user-attachments/assets/3b90c7e0-e5e0-455f-927d-1f9e7e61f7fc)
this is just content. and also add links and contact icons. and so on...

and i well make design according to the website.

**Comment by ShashwatAgrawal20** [comment]
@Wahid7852 @BhattAnsh ig we can assign this guy?

**Comment by techy4shri** [comment]
Closing this as we will be wrapping up now. No new designs and discussion atm.
