### ISSUE TITLE
Feat: RateUs functionality

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#127]
# 🚀 QuizQuest Issue Tracker

### 🌟 Feature Request

**Title**: RateUs functionality

**Description**:
- **Overview**: There is no RateUs Functionality in website.
- **Benefits**:  It increases user attraction via rating
- **Possible Implementation**: I will add separate feature of rating us functionality.

@BhattAnsh Please assign this issue to me with level-3:)

**Comment by harshbhar0629** [comment]
@BhattAnsh ??

**Comment by harshbhar0629** [comment]
@BhattAnsh please assign

**Comment by techy4shri** [comment]
@BhattAnsh deosn't look like we need it but check it.
He has been assigned an issue already.
