### ISSUE TITLE
ContactUs Backend Functionality 

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#132]
# 🚀 QuizQuest Issue Tracker

### 🌟 Feature Request

**Title**: ContactUs Backend Functionality 

**Description**:
- **Overview**: There is no way to connect user with you suppose i have a query then how can i connect with you there is no way except social media. 
- **Benefits**: User can directly interact with you via contact us functionality. 
- **Possible Implementation**: I will use email js for contacting us functionality because this is simple implementation what i also prefer.

@BhattAnsh please assign this task to me with **gssoc-ext and level-3 or level-2** tag.

**Comment by techy4shri** [comment]
1. Do not ask for level, it will be assigned directly as per your work.
2. Do not create numerous issues at once or create PR without being assigned.
3. Explain where will you add this and why is it needed.

**Comment by BhattAnsh** [comment]
@harshbhar0629 about contact us Backend we are going to work on that part and decide the approach....
