### ISSUE TITLE
The Create Now button is not working 

### ISSUE THREAD

**Issue by Mansi-Tanwar** [BhattAnsh/Quiz-Quest#134]
### 🐞 Bug Report

**Title**: The Create Now button is not working 

**Description**:
The Create Now button is not working. If I click on it, nothing opens up to create a quiz. If you assign this task to me, I would love to work on the issue. 
- **Expected Result**: It should show interface to add questions or create quiz. 
- **Actual Result**: nothing happens. 
- **Screenshots**![image](https://github.com/user-attachments/assets/05e2ac69-9c4e-4208-bcde-a145b8e099d8)
  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

**Comment by techy4shri** [comment]
Explain your approach. @BhattAnsh please look into this. @Mansi-Tanwar discuss in detail on discord, if Ansh approves.

**Comment by Mansi-Tanwar** [comment]
@techy4shri i have already submitted the pull request even before wahid closed this as not planned and the pull request is also already merged. #140

**Comment by BhattAnsh** [comment]
@techy4shri the pr related to this issue is merged so I am going to close this issue

**Comment by BhattAnsh** [comment]
Pr is merged
