### ISSUE TITLE
I want to solve the button and navbar issue

### ISSUE THREAD

**Issue by sambedan1** [BhattAnsh/Quiz-Quest#135]
# 🚀 QuizQuest Issue Tracker

Welcome to the **QuizQuest** issue tracker! Please follow the guidelines below to report issues or suggest enhancements.

## How to Create an Issue

1. **Search for Existing Issues**: Before creating a new issue, please check if your issue or feature request has already been reported.
2. **Use the Appropriate Template**: Choose one of the templates below for your issue type.

### 🐞 Bug Report

**Title**: [Short description of the bug]

**Description**:
- **Steps to Reproduce**:
  1. Step one
  2. Step two
  3. Step three
- **Expected Result**: What you expected to happen
- **Actual Result**: What actually happened
- **Screenshots**: (if applicable)
  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

**Additional Information**: (any other relevant details)

---

### 🌟 Feature Request

**Title**: [Short description of the feature]

**Description**:
- **Overview**: Briefly describe the feature you want to suggest.
- **Benefits**: Explain why this feature would be valuable to users.
- **Possible Implementation**: (optional) Suggest how this feature might be implemented.

---

### 💬 General Question or Discussion

**Title**: [Short description of the question]

**Description**:
- **Question**: Clearly state your question or topic of discussion.
- **Context**: Provide any relevant context that might help in answering your question.

---

## Guidelines for Issues

- Please be respectful and constructive in your feedback.
- If you are submitting a bug report, please include as much detail as possible to help us reproduce the issue.
- For feature requests, consider providing examples of how the feature could improve the application or user experience.

## Thank You!

Thank you for contributing to the **QuizQuest** project! We appreciate your feedback and support in making our application better.

**Comment by Wahid7852** [comment]
Fill the issue Template first @sambedan1

**Comment by ShashwatAgrawal20** [comment]
Sorry, 

![its-a-little-bit-vague-adam](https://github.com/user-attachments/assets/f3413f9d-841e-4303-b8d8-2dbd33b57425)
