### ISSUE TITLE
Add 'Theme Selection' Feature for Quiz Customization

### ISSUE THREAD

**Issue by 0xPratikPatil** [BhattAnsh/Quiz-Quest#14]
**Description:** 
I would like to implement a feature that allows users to select a theme for their quiz interface, as shown in the attached image. This feature should provide options like default themes, customizable themes, and user-specific themes. Each theme can be previewed and edited by the user to match the quiz style.

**Features to include**:
1. **Theme Categories**:
   - Default Themes
   - Customize
   - User Themes

2. **Editable Options**:
   - Users should be able to select and preview themes.
   - An 'Edit' button should allow users to customize the chosen theme.
   
   **Could you please assign this issue to me under GSSOC'24 extd?**

**Comment by BhattAnsh** [comment]
thats's a great idea join our discord and contact frontend dev who are working there  https://discord.gg/XBBgKkBT
