### ISSUE TITLE
BUG: No Password view icon in forms

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#141]
# 🚀 QuizQuest Issue Tracker

**Title**: [Short description of the bug]

**Description**: There is no password view icon in signup and login form.
- **Steps to Reproduce**:
  1. Add view icon and also add conditional rendering.
- **Expected Result**: User can view our password so that he knows what he is trying to enter and what he/she enter.
- **Actual Result**: Nobody can view our password.
- **Screenshots**: 

![login](https://github.com/user-attachments/assets/c251e137-3156-4fb1-9c70-22392e3b8472)

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

**Comment by ShashwatAgrawal20** [comment]
@harshbhar0629 You're the wizard for this one! Let's make magic happen! 

![assigned](https://github.com/user-attachments/assets/b3718acb-d19f-4b34-b9c3-f7dbc456ba10)
