### ISSUE TITLE
BUG: Signup Btn Not Working Login-Page

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#142]
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: Signup btn not working in login page.

**Description**:
- **Steps to Reproduce**:
  1. When we click on signup btn then it navigates to signup form

- **Expected Result**: When user don't have account then it will signup first but there is no way to navigate in signup form.
- **Actual Result**: When we click on signup btn then it will not navigates to signup page.
- **Screenshots**:

https://github.com/user-attachments/assets/9ee31331-ae5a-4fc0-bfcd-8f36f4ec6405

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

**Comment by ShashwatAgrawal20** [comment]
make sure you're checking stuff off the development branch by locally running the website.

![it-already-exists](https://github.com/user-attachments/assets/0cc48eef-924a-417e-a62b-c3bd29c18bed)

**CLOSING**
