### ISSUE TITLE
BUG: ContactUs Page Link not working

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#143]
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: In footer when we click on contact us link then it navigates to not found page but contactUs page exist.

**Description**:
- **Steps to Reproduce**:
  1. We have to update the path of contact us.

- **Expected Result**: When we click on contactUs page then it navigates to contact us page.
- **Actual Result**: There is no behaviour at all to navigates to contactUs page it navigates to not found page.
- **Screenshots**: 

https://github.com/user-attachments/assets/86e39760-d9e6-46b2-bb84-3f8230a4c97d

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

**Comment by harshbhar0629** [comment]
@BhattAnsh please assign

**Comment by ShashwatAgrawal20** [comment]
@harshbhar0629 
You're the wizard for this one! Let's make magic happen! 

![assigned](https://github.com/user-attachments/assets/10136062-1315-4b2d-9f18-d061a52c2042)

**Comment by nithin17298** [comment]
@BhattAnsh  Please assign this issue
