### ISSUE TITLE
Custom: No Privacy-Policy page

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#144]
# 🚀 QuizQuest Issue Tracker

### 🌟 Custom Report

**Title**: No Privacy Policy page in website.
**Description**:
- **Steps to Reproduce**:
  1. Adding whole page of privacy policy
  
- **Expected Result**: We want to add Privacy policy page.
- **Actual Result**: There is no privacy policy page.

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me:)

**Comment by harshbhar0629** [comment]
@BhattAnsh please assign

**Comment by harshbhar0629** [comment]
@BhattAnsh please assign.?

**Comment by ShashwatAgrawal20** [comment]
what are you going to write in the privacy policy page? Do you have some idea in your mind?

CC: @BhattAnsh
