### ISSUE TITLE
BUG: Improve UI 404 Page

### ISSUE THREAD

**Issue by harshbhar0629** [BhattAnsh/Quiz-Quest#145]
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: Improve UI of not found page.

**Description**:
- **Steps to Reproduce**:
  1. UI editing

- **Expected Result**: In 404 page everything visible properly.
- **Actual Result**: There is very bad UI now of 404 page.
- **Screenshots**: 

  
![improveUI](https://github.com/user-attachments/assets/b1780d8d-10a4-4582-a608-85eeee833398)

**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

**Comment by BhattAnsh** [comment]
I will assign you this issue but few points you have to keep in your mind 

1. Make the theme as same as our homepage (green and black hex is give in the repo you can check it out)
2. use Svg or lottifiles only which should not get distorted.
3. Make sure you keep your repo updated and don't have any conflicts with the development branch and always make PR in development branch.

**Comment by techy4shri** [comment]
Removing the level label, the level will be decided based on the PR.

**Comment by techy4shri** [comment]
closing this as we are not accepting any new PRs now.
