### ISSUE TITLE
Sign up page 

### ISSUE THREAD

**Issue by Aditya90456** [BhattAnsh/Quiz-Quest#146]
adding sign up page 
![design-deck vercel app_signup and 7 more pages - Personal 2 - Microsoft​ Edge Beta 11_1_2024 3_20_32 PM](https://github.com/user-attachments/assets/b4584c2c-02d9-4626-8909-1356ee321a82)

**Comment by ShashwatAgrawal20** [comment]
@Aditya90456 You're the wizard for this one! Let's make magic happen! 

![assigned](https://github.com/user-attachments/assets/dd3ead0b-ad8a-4c82-a656-d317f40744f1)

**Comment by Aditya90456** [comment]
okk

**Comment by ShashwatAgrawal20** [comment]
btw @Aditya90456 the signup page already exits, so you just have to link that to the signup button on the login page.

**Comment by Aditya90456** [comment]
npm is not start @ShashwatAgrawal20

**Comment by ShashwatAgrawal20** [comment]
> npm is not start @ShashwatAgrawal20

what's the issue?

**Comment by Aditya90456** [comment]
website can't run @ShashwatAgrawal20

**Comment by ShashwatAgrawal20** [comment]
@Aditya90456 closing this issue as @BhattAnsh himself is going to fix this.

Sorry for the inconvenience.
