### ISSUE TITLE
Adding a metrices table and program section

### ISSUE THREAD

**Issue by Aman-G-upta** [BhattAnsh/Quiz-Quest#149]
![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/17ec9242-53a5-44ab-82ac-55f0a95e0925)
Please assign me under this issue @BhattAnsh

**Comment by ShashwatAgrawal20** [comment]
Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/c5ca9bc9-9b17-4f2a-91a6-dccadcf3b7b0)


**CLOSING**
