### ISSUE TITLE
Building Registration Form

### ISSUE THREAD

**Issue by tanmayghosh01-hue** [BhattAnsh/Quiz-Quest#15]
I will create Login and Registration form based on given UI.

**Comment by ravi-kumar2003** [comment]
I came across this issue, and I would love to help contribute to resolving it.

**Comment by Sarthakkashyapp** [comment]
Hi @BhattAnsh I would like to contribute on this issue

**Comment by tarunkumar2005** [comment]
@BhattAnsh The issue is assigned from two weeks still not fixed can you assign this to me i will work on this issue.

**Comment by CodeVoyge** [comment]
I would like to contribute on this issue , could you please assign this to me??

**Comment by harshbhar0629** [comment]
@BhattAnsh Please assign to me:)
