### ISSUE TITLE
feat: Contact us page

### ISSUE THREAD

**Issue by AE-Hertz** [BhattAnsh/Quiz-Quest#150]
# 🚀 QuizQuest Issue Tracker

Welcome to the **QuizQuest** issue tracker! Please follow the guidelines below to report issues or suggest enhancements.

feat: to add a contact us page 

assign me this under hacktoberfest and gssoc-ext @BhattAnsh

**Comment by ShashwatAgrawal20** [comment]
![it-already-exists](https://github.com/user-attachments/assets/71d3fff1-c764-4d81-9a9d-af9d04416ce2)

**CLOSING**
