### ISSUE TITLE
feat: term of servies page

### ISSUE THREAD

**Issue by AE-Hertz** [BhattAnsh/Quiz-Quest#151]
# 🚀 QuizQuest Issue Tracker

Welcome to the **QuizQuest** issue tracker! Please follow the guidelines below to report issues or suggest enhancements.

feat: term of servies page with matching the the current theme,

Assign me this under hacktoberfest and gssoc-ext @BhattAnsh

**Comment by ShashwatAgrawal20** [comment]
@AE-Hertz what are you going to add in that page? 

Can you first share your implementation idea.
