### ISSUE TITLE
Login, Sign Up, Explore, and Continue with Google Buttons Not Working

### ISSUE THREAD

**Issue by gamana29** [BhattAnsh/Quiz-Quest#152]
Title: Login, Sign Up, Explore, and Continue with Google Buttons Not Working

Description: The Login, Sign Up, Explore, and Continue with Google buttons on the main page are unresponsive. Clicking on them does not trigger any action or redirect the user as expected.

Steps to Reproduce:

Open the main page where the buttons are located.
Attempt to click on each of the following buttons: Login, Sign Up, Explore, and Continue with Google.
Observe that no actions occur when clicking these buttons.
Expected Result: Clicking on each button should initiate the respective actions: logging in, signing up, exploring content, or logging in via Google.

Actual Result: None of the buttons respond when clicked, and no actions are taken.

Screenshots: (Add any relevant screenshots if available)

Environment:

Operating System: (e.g., Windows 10, macOS Ventura)
Browser: (e.g., Chrome 117, Firefox 118)
Version: (e.g., QuizQuest v1.0)
Additional Information: Please investigate button event listeners and related JavaScript functions to ensure they are correctly linked.

**Comment by ShashwatAgrawal20** [comment]
Please don't check the hosted version, you should be running the version from the development branch locally. 

The Login and Signup buttons are working there's a problem with `Continue with Google` and `Explore` button which is besides the Login button on the navbar. 

Let's see what PA has to say. 

CC: @BhattAnsh

**Comment by ShashwatAgrawal20** [comment]
stale
