### ISSUE TITLE
Not a suited scrollbar for your website

### ISSUE THREAD

**Issue by VinayLodhi1712** [BhattAnsh/Quiz-Quest#153]
### 🌟 Feature Request

**Title**: I can add suited scrollbar for your website right now it is showing default scrollbar

**Description**:

- **Benefits**: Suits on your website.

https://github.com/user-attachments/assets/b3855c7e-fe8c-4437-b52f-779d4dbddaf6

![scrollbar3](https://github.com/user-attachments/assets/1d8ba232-91c4-458f-ae45-8c06336b7bf9)

**Comment by ShashwatAgrawal20** [comment]
ayoo @BhattAnsh do we need this?

**Comment by techy4shri** [comment]
closing this because we are wrapping up now and won't be accepting any new PRs.
