### ISSUE TITLE
add UI design in explore page

### ISSUE THREAD

**Issue by niteshkr100** [BhattAnsh/Quiz-Quest#154]
# 🚀 QuizQuest Issue Tracker

**Title**:  Add some design on the explore page

**Description**:
 This page is totally empty and only footer is seen. So, I want to add some design to make it look more better and attractive.

@BhattAnsh, please assign me this task  with labels.

**Comment by ShashwatAgrawal20** [comment]
@niteshkr100 hi, please make sure you check stuff on the development branch, the deployment is from the main branch which is quite behind the `development`, make sure to run the project locally via `development` branch. 

![it-already-exists](https://github.com/user-attachments/assets/3dcb0225-137c-4034-9d42-47c0751bfca7)

**CLOSING**

**Comment by niteshkr100** [comment]
okay
