### ISSUE TITLE
Duplicate icon is shown in mobile view in navbar

### ISSUE THREAD

**Issue by niteshkr100** [BhattAnsh/Quiz-Quest#155]
# 🚀 QuizQuest Issue Tracker

### 🌟 Feature Request

**Title**: [ Add a new icon and remove duplicate in navbar as shown in mobile view]

**Description**:
- **Overview**: There is duplicate search icon and contact icon is there .
- **Benefits**: By chaning duplicate icon and adding correct icon we get clear view what is is the use of the icon in navbar .
  
**Screenshot **:
<img width="800" alt="Screenshot 2024-11-06 at 2 47 17 PM" src="https://github.com/user-attachments/assets/c7a295b1-a645-4b30-8111-ac46752b4346">

@BhattAnsh, please assign me this task to fix this issue with labels.

**Comment by BhattAnsh** [comment]
Make sure that pr in development branch

**Comment by niteshkr100** [comment]
Thank you for your help and support @BhattAnsh & @techy4shri

**Comment by techy4shri** [comment]
Happy to help Nitesh!
