### ISSUE TITLE
Design and Integration of Logo for QuizQuest Website

### ISSUE THREAD

**Issue by Swati-bs** [BhattAnsh/Quiz-Quest#158]
**Feature Description:**
This feature will involve creating a unique logo for the QuizQuest website and integrating it across key areas to establish a cohesive visual identity and enhance brand recognition.

**Custom Logo Design:**
- [ ]  Design a logo that encapsulates QuizQuest's brand values and mission.
- [ ]  Ensure the design is versatile and adaptable for different formats (e.g., web, favicon, and mobile use).

**Integration:**
- [ ]  Add the logo to the header, ensuring it’s prominently visible on all pages.

**Record**
- [x]  I agree to follow this project's Code of Conduct
- [x]  I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by techy4shri** [comment]
Closing this as we are  wrapping up and any furthuer discussions will be done afterwards.
