### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [BhattAnsh/Quiz-Quest#16]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @BhattAnsh please assign me this task with labels "gssoc-ext", "hacktoberfest-accepted" and "level1"

**Comment by BhattAnsh** [comment]
Can you explain to me the approach of how you will do it that's a great idea to implement ?

**Comment by samyak-aditya** [comment]
Hi @BhattAnsh,

Thank you for considering my proposal! Here’s how I plan to implement the "Greetings" workflow:

### Approach

1. **GitHub Actions**: I'll create a new workflow file in the `.github/workflows` directory of the repository. This file will define the triggers for the workflow, specifically for new issues and pull requests.

2. **Events**: The workflow will be triggered by the `issues` and `pull_request_target` events. This means it will activate whenever a new issue is opened or a pull request is created.

3. **Using Existing Actions**: To simplify the implementation, I plan to use the `actions/first-interaction` action. This action is designed to automatically comment on issues and pull requests made by new contributors.

4. **Custom Messages**: I will customize the greeting messages for both issues and pull requests. For example:
   - For issues: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
   - For pull requests: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

5. **Permissions**: The workflow will require appropriate permissions to post comments on issues and pull requests. I'll ensure that the permissions are correctly configured in the workflow file.

6. **Testing**: After implementing the workflow, I will create a test issue and pull request to ensure that the greetings are posted correctly and the functionality works as expected.

### Conclusion

I believe this workflow will enhance our community engagement by providing a warm welcome to new contributors, encouraging more participation in the project.

**Comment by BhattAnsh** [comment]
Ya sure that's what I wanted to do join my discord server we will discuss about this there okay? https://discord.gg/u2N6rsa8

**Comment by BhattAnsh** [comment]
@samyak-aditya should I assign you this issue now?

**Comment by samyak-aditya** [comment]
Yes @BhattAnsh assign it to me

**Comment by samyak-aditya** [comment]
Hey @BhattAnsh I have raised the PR
Do let me know if you also need and kind for auto-labeler for when issues are created
