### ISSUE TITLE
Adding A ChatBot

### ISSUE THREAD

**Issue by satyam969** [BhattAnsh/Quiz-Quest#160]
🌟 Feature Request
Title: Add Chatbot Integration to QuizQuest

Description:

Overview: Integrate a chatbot into the QuizQuest website to assist users with navigation, answer common questions, and provide help on quiz topics.
Benefits: A chatbot would enhance user experience by providing instant support, helping users find quizzes, answering FAQ, and potentially offering hints or explanations on quiz questions. This feature would make QuizQuest more user-friendly and accessible, especially for new users who may need guidance.
Possible Implementation:
Use a chatbot platform like Dialogflow, IBM Watson, or a custom NLP model.
Implement basic features like FAQs, quiz recommendations, and account assistance.
Integrate the chatbot interface as a widget on the QuizQuest homepage for easy access.
Additional Information: Part of GSSOC-24 initiative, extending interactive functionality on QuizQuest to improve user engagement and accessibility

**Comment by techy4shri** [comment]
not needed atm, we are wrapping up.
