### ISSUE TITLE
add /me route in backend

### ISSUE THREAD

**Issue by ak3264114** [BhattAnsh/Quiz-Quest#2]
The authenticateToken middleware checks if the request contains a valid JWT token.
If valid, the /me route returns a response indicating the user is logged in

this route will help to check that is user is logged in not when user revisit on the website

**Comment by ak3264114** [comment]
Assign this issue to me

**Comment by BhattAnsh** [comment]
Join Discord- https://discord.gg/jDDHucBaE8 I will share the details there and will have a meeting also
