### ISSUE TITLE
The Readme file needs an update!!

### ISSUE THREAD

**Issue by Kishore007raj** [BhattAnsh/Quiz-Quest#27]
Hello There!, I have noticed a bug in the README file where the link to the Contributing Guidelines page redirects to some other page, which also goes for the License page. I would like to work on this issue and make necessary improvements to the README file 

If this issue can be assigned to me, I am eager to contribute and make the README file more user-friendly and informative.!!
![Screenshot (683)](https://github.com/user-attachments/assets/1c074cab-6104-4293-81e2-be3d0f82a425)
![Screenshot (682)](https://github.com/user-attachments/assets/8ae8fae6-be73-4351-a9b4-a44731b00605)

**Comment by khushidadwal** [comment]
Can't see any development in the Readme.md file. The current readme file looks very dull and simple. I can enhance it to look more attractive and tempting.
@TeekshaHarish please assign this issue to me.
Thanks :-)

**Comment by TeekshaHarish** [comment]
@Kishore007raj are you still working on this issue, what's the update?

**Comment by Kishore007raj** [comment]
I have already given the pull request regarding the completion of work 2 weeks but it seems like the project maintainer has closed the pull request without checking it .So please look at it 
Here is the proof ,if you want to check it ![Screenshot_20241018_034756.jpg](https://github.com/user-attachments/assets/022d8e72-eec3-4fbe-ad70-5912d1b99b20)

**Comment by Kishore007raj** [comment]
![Screenshot_20241018_035210.jpg](https://github.com/user-attachments/assets/b3cbbfbd-b141-4819-a769-80c9ddf9a189)

**Comment by BhattAnsh** [comment]
Sorry @Kishore007raj I thought it was another spam pr.... Can u raise another pr

**Comment by BhattAnsh** [comment]
@Kishore007raj make sure that I pulled the repo then made changes accordingly so there will be no conflicts

**Comment by Kishore007raj** [comment]
Hello there!! I have given my new Pull request regarding this one...please check on it 

This is the pr name - "[Completed} - "The Readme file needs an update!! #87 ""
