### ISSUE TITLE
Scoring System of the Quizes

### ISSUE THREAD

**Issue by yours7himanshu** [BhattAnsh/Quiz-Quest#33]
@BhattAnsh 
We should create a scoring section of the quizes and rank them according to there score.

**Comment by BhattAnsh** [comment]
@yours7himanshu yep we have to work on that part join discord https://discord.gg/u2N6rsa8

**Comment by yours7himanshu** [comment]
> @yours7himanshu yep we have to work on that part join discord https://discord.gg/u2N6rsa8

So are u going to assign that to me?
