### ISSUE TITLE
Provide Live Link of the project

### ISSUE THREAD

**Issue by YOGINIMAHIMA1** [BhattAnsh/Quiz-Quest#34]
This is major issue you need to provide deployment link of project @BhattAnsh

**Comment by YOGINIMAHIMA1** [comment]
Also add label ex gssoc-ext to this issue

**Comment by BhattAnsh** [comment]
@YOGINIMAHIMA1 will work on that once the frontend is ready

**Comment by YOGINIMAHIMA1** [comment]
@BhattAnsh add label of gssoc-ext to this issue
