### ISSUE TITLE
Building frontend

### ISSUE THREAD

**Issue by Bhum-ika** [BhattAnsh/Quiz-Quest#4]
Assign this issue to me , I can start working on it then.

Please add gssoc24ext and hactoberfest tags

**Comment by BhattAnsh** [comment]
Join Discord- https://discord.gg/jDDHucBaE8 I will share the details there and will have a meeting also

**Comment by Bhum-ika** [comment]
Showing invalid invite

**Comment by BhattAnsh** [comment]
https://discord.gg/kx2d2gYxza this will work
