### ISSUE TITLE
Create Explore page and Login Page

### ISSUE THREAD

**Issue by yeshwanth-ds** [BhattAnsh/Quiz-Quest#49]
![Screenshot 2024-10-08 191704](https://github.com/user-attachments/assets/882b7309-849a-4878-af5c-81249ae9d771)

# Quiz Quest - Front-end

**Where knowledge meets fun!**  
This repository focuses on the front-end development of the **Quiz Quest** website, specifically for the **Login** and **Explore** pages.

---

## Project Overview

**Quiz Quest** is an interactive platform that allows users to build, join, and host quizzes within a community of quiz enthusiasts. The front-end plays a vital role in delivering an intuitive user experience, ensuring smooth navigation, and making quiz exploration seamless.

### Key Front-end Features

1. **Login Page**  
   Provides a secure and user-friendly interface for users to log in or register to the platform.

2. **Explore Page**  
   Allows users to browse and search for quizzes based on categories, difficulty levels, or popularity.

---

### 1. Login Page

The **Login Page** is crucial for user authentication, allowing users to sign in or register to access the platform's features.

#### Key Requirements:
- **User-Friendly Interface**: Simple form design for logging in with email and password.
- **Third-party Integration**: Option to log in using Google or Facebook for ease of access.
- **Responsive Design**: The page must be fully responsive, offering seamless experience on mobile devices.

#### Benefits:
- **Secure Access**: Ensures that user data and quiz progress are protected.
- **Personalization**: Once logged in, users can create, host, and track quizzes they’ve participated in.
- **Convenience**: Third-party login options provide a quick and easy way for users to access the platform.

---

### 2. Explore Page

The **Explore Page** serves as the core navigation hub for users to discover and participate in quizzes.

#### Key Requirements:
- **Search Functionality**: Users should be able to search quizzes by name, category, or creator.
- **Filter Options**: Provide filters such as quiz difficulty, popularity, and recent activity.
- **Responsive Design**: Ensure the page is accessible across all device types, from desktop to mobile.

#### Benefits:
- **Efficient Quiz Discovery**: Users can quickly find quizzes that match their interests or skill levels.
- **Engagement**: The explore page encourages users to participate in community-created quizzes, enhancing user retention.
- **Accessibility**: By providing filters and search options, the platform becomes more user-friendly and navigable.

---
I would like you to assign me this task under hacktoberfst and gssoc-ext with level tag

**Comment by BhattAnsh** [comment]
@yeshwanth-ds The contributors are working on these parts if you want to contribute join - https://discord.gg/2vHVCdA4 so we can plan and work accordingly thankyou
