### ISSUE TITLE
Login And Registration form

### ISSUE THREAD

**Issue by Mdraza78** [BhattAnsh/Quiz-Quest#5]
create Login And Registration form

**Comment by meghanakn473** [comment]
HEY @Mdraza78 please assign me this issue, i want to work on it.

**Comment by TanishValesha** [comment]
Hey @Mdraza78 please assign me this issue, as I have already implemented Login and Registration feature in my several personal projects

**Comment by divya7202** [comment]
dear admin, would you please assign this issue to me

**Comment by BhattAnsh** [comment]
@divya7202 @TanishValesha @meghanakn473 https://discord.gg/u2N6rsa8 join discord I will keep informing of new issue

**Comment by shanmukhi-developer** [comment]
Hey @Mdraza78 please assign me this issue, as I have already implemented Login and Registration feature in some projects.
