### ISSUE TITLE
Add a new "Create" Page

### ISSUE THREAD

**Issue by yeshwanth-ds** [BhattAnsh/Quiz-Quest#50]
# Quiz Quest

**Where knowledge meets fun!**  
Build, join, and host quizzes with a community of quiz enthusiasts.

---

## Project Overview

**Quiz Quest** is an interactive platform designed for users to build, join, and host quizzes. This project aims to create a smooth user experience where users can participate in quizzes and also create their own quizzes, contributing to a community of quiz lovers.

### Upcoming Feature: Create Quiz Page

As part of expanding the platform, we are requesting to implement a **Create Quiz** page where users can create custom quizzes by providing a quiz title, multiple questions, and options. The system will store correct answers in an array or object for later comparison.

### Key Requirements for Create Quiz Page

- **Quiz Title**: Users should be able to input the name of their quiz.
- **Questions and Options**: Each quiz will allow multiple questions. For each question:
  - Provide 4 multiple-choice options.
  - Indicate the correct option for each question.
- **Data Structure**: Store the quiz, questions, and answers in an object or array format.
  - Example structure:
    ```javascript
    const quiz = {
      title: "Sample Quiz",
      questions: [
        {
          question: "What is the capital of France?",
          options: ["Paris", "London", "Berlin", "Madrid"],
          correctAnswer: "Paris"
        },
        {
          question: "Who discovered penicillin?",
          options: ["Alexander Fleming", "Marie Curie", "Isaac Newton", "Albert Einstein"],
          correctAnswer: "Alexander Fleming"
        }
      ]
    };
    ```

---

## Request to Admin

We are requesting the admin to assign the task of creating the **Create Quiz** page under the following initiatives:

- **Hacktoberfest**
- **GSSoC-Ext**

Please assign this task under the appropriate difficulty level tags based on the complexity, so contributors can pick the relevant level.

---

## Contribution Guidelines

If you are contributing to the **Create Quiz Page** task, here’s how you can get started:

### Task

| Task                     | Description                                               | Difficulty Level |
| ------------------------- | --------------------------------------------------------- | ---------------- |
| **Create Quiz Page**      | Build a page to allow users to create quizzes and store data. | Intermediate - difficult    |

**Comment by BhattAnsh** [comment]
@yeshwanth-ds we are planning to work on this page if you want to work join - https://discord.gg/2vHVCdA4

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd
