### ISSUE TITLE
Implement User Feedback System

### ISSUE THREAD

**Issue by 23WH1A0507** [BhattAnsh/Quiz-Quest#57]
Create a user feedback system that allows users to submit feedback about their quiz-taking experience. This could include ratings for quizzes, comments on question quality, and suggestions for improvements. The feedback collected should be displayed in an admin dashboard for review.

**Comment by BhattAnsh** [comment]
this will be implemented but first we focusing on creating a platform when the main components and functionality will be developed we will work on this issue. Thanks for you suggestion

**Comment by 23WH1A0507** [comment]
I’ve implemented the Dark Mode toggle feature as discussed. Users can now easily switch between light and dark themes, enhancing usability in low-light environments. The feature remembers their preference for future visits.

Feel free to check it out and let me know if you have any feedback or suggestions!
