### ISSUE TITLE
Add a footer section 

### ISSUE THREAD

**Issue by yeshwanth-ds** [BhattAnsh/Quiz-Quest#61]
Adding a footer section with relavent information and links.

I would like you to assign me this task and hacktoberfest and gssoc-ext with level tag

**Comment by student-nitjalandhar** [comment]
@yeshwanth-ds please assign this to me

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd

**Comment by tarunkumar2005** [comment]
@BhattAnsh I can see the issue is open from last week still not fixed can you assign this to me i will work on this issue.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me.. i can design a very nice footer
