### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by haseebzaki-07** [BhattAnsh/Quiz-Quest#63]
I want to dockerize this application to run it inside docker container ensuring smooth development and deployment across all systems.

Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

**Comment by BhattAnsh** [comment]
Can you please join the discord so we can discuss it properly with other active developers ? link - https://discord.gg/2vHVCdA4

**Comment by haseebzaki-07** [comment]
Hey @BhattAnsh the link seems invalid. Can you please share me the link again?

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd
