### ISSUE TITLE
Want to expand the contributer section 

### ISSUE THREAD

**Issue by Vyshnavi1322** [BhattAnsh/Quiz-Quest#65]
i will work on this assign me this issue @BhattAnsh

**Comment by BhattAnsh** [comment]
can you explain me what do you mean by "Want to expand the contributor section?"

**Comment by Vyshnavi1322** [comment]
how to do forking and braching and code style guide and commit changes

**Comment by Vyshnavi1322** [comment]
Assign me this I will work on this @BhattAnsh

**Comment by BhattAnsh** [comment]
sorry not assigning the readme file issues to anyone you can contribute to some other issues
