### ISSUE TITLE
Fix Quiz Schema and work on quiz APIs

### ISSUE THREAD

**Issue by BhairabMahanta** [BhattAnsh/Quiz-Quest#67]
**Description:**
We have identified several updates to be required with the current quiz schema and its associated APIs. These issues are affecting the functionality and reliability of the quiz feature. The primary goals of this issue are to refine the quiz schema and debug the existing APIs to ensure they work as intended.

**Tasks:**

1. **Update Quiz Schema:**
   - Analyze the current quiz schema and identify the missing fields.
   - Ensure the schema accommodates various question formats (e.g., MCQ, multiple correct answers, integer, and string answers).
   - Implement any necessary changes to the schema to enhance flexibility and maintainability.

2. **Debug Quiz APIs:**
   - Investigate the existing APIs related to quiz creation, retrieval, updating, and deletion.
   - Identify any issues causing them to not function as intended.
   - Integrate API based on google forms requests.
   - skip the one's that require quiz authentication as it'll be optimistic to keep it for a newer PR.

3. **Documentation:**
   - Update any relevant documentation to reflect the changes made to the schema and APIs.
   - Ensure that other team members are aware of the modifications and how to use the updated APIs.
---
**Request**
Assignee: Assign me!
Labels: `gssoc ext`, `hacktoeberfest`, `levels` @BhattAnsh

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd

**Comment by BhairabMahanta** [comment]
merged issue solved it
