### ISSUE TITLE
Add Signin & Login Functionality

### ISSUE THREAD

**Issue by Mdraza78** [BhattAnsh/Quiz-Quest#7]
Currently, the application lacks a proper Sign In and Login system, preventing users from accessing personalized features.

Proposed Solution:
Implement both Sign In and Login functionality:

Sign In: Allow new users to create an account with their details (e.g., name, email, password).
Login: Enable existing users to log in using their registered credentials.

**Comment by BhattAnsh** [comment]
Have you seen the backend code? Login logout feature is there with proper authentication and authorisation. 

We have to work on the frontend.

Join https://discord.gg/kx2d2gYxza for more discussion

**Comment by meghanakn473** [comment]
HEY @Mdraza78 please assign me this issue, i want to work on it.
