### ISSUE TITLE
Improvising the Data Modelling

### ISSUE THREAD

**Issue by MOHINI1403** [BhattAnsh/Quiz-Quest#8]
The models designed for users can be improved by adding the multer middleware and adding the code for allowing the avatar and coverImage to be added , along with this enhancing the code quality . 
Please assign this issue to me.

**Comment by BhattAnsh** [comment]
hmm looks an interesting issue can you join Discord server where we can discuss more - https://discord.gg/kx2d2gYxza

**Comment by MOHINI1403** [comment]
Sure I will join the channel.

**Comment by MOHINI1403** [comment]
Can you assign me the issue so that I can work on this.
