### ISSUE TITLE
🌟 Feature Request: Automated project structure updation using github workflows, python scripts and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [BhattAnsh/Quiz-Quest#91]
### 🌟 Feature Request

**Title**: Automated project structure updation using github workflows, python scripts and action bot

**Description**:
- **Overview**: Automated project structure updation using github workflows, python scripts and action bot
- **Benefits**: Currently, we dont have the automated project structure updation in our repository. It'll be benefitial for the new commers to understand the project structure from readme itself and reduces the manual work as well. 
- **Possible Implementation**: Using worksflows and scripts in python

Sample: 

![image](https://github.com/user-attachments/assets/26bbda18-4082-4d17-8222-1488fbcdb3fb)

---

**Comment by BhattAnsh** [comment]
start working on this issue
